### ISSUE TITLE
CaptureSagaStateBehavior throws when handling reply type handled by multiple sagas

### ISSUE THREAD

**Issue by timbussmann** [NServiceBusExtensions/NServiceBus.Serilog#16]
When multiple sagas handle the same message type which is used as a reply message, the `CaptureSagaStateBehavior` throws an exception.
This can happen because a reply message is specific to a single saga instance. The `SagaPersistenceBehavior` in core detects these cases (that has been fixed recently) and only invokes the handler on the saga which the reply was intended for while skipping other sagas with the same handler.

As the `CaptureSagaStateBehavior` runs before the `SagaPersistenceBehavior` it will be invoked for every saga, regardless of whether the pipeline will be shortcut later (and not contain a `ActiveSagaInstance`).

See this discourse thread for more information: https://discuss.particular.net/t/nsb7-multiple-sagas-handle-the-same-message/612

**Comment by SimonCropp** [comment]
this is now deployed. it may take nuget up to an hour to re-index
