### ISSUE TITLE
Message tracing and property encryption

### ISSUE THREAD

**Issue by Rensvind** [NServiceBusExtensions/NServiceBus.Serilog#172]
Hi!

I'm trying to get NServiceBus property encryption to work with message tracing but it seems like the LogOutgoingMessageBehavior is applied before the encryption so the real value is logged instead of the encrypted one. Would it be possible to add

`InsertAfterIfExists("MessagePropertyEncryption");`

to the register step of LogOutgoingMessageBehavior?

**Comment by SimonCropp** [comment]
https://github.com/NServiceBusExtensions/Home/blob/master/readme.md

**Comment by SimonCropp** [comment]
https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq

**Comment by SimonCropp** [comment]
closing for now. feel free comment back here when your company becomes a patron
