### ISSUE TITLE
ArgumentNullException at Serilog.Events.LogEvent.AddOrUpdateProperty

### ISSUE THREAD

**Issue by Craigology** [NServiceBusExtensions/NServiceBus.Serilog#20]
Upon enabling Serilog tracing using [4.01](https://github.com/NServiceBusExtensions/NServiceBus.Serilog/releases/tag/4.0.1) of NServiceBus.Serilog and NServiceBus.Serilog.Tracing,  I am encountered the same `ArgumentNullException` at `Serilog.Events.LogEvent.AddOrUpdateProperty(LogEventProperty property)` referenced in: https://github.com/NServiceBusExtensions/NServiceBus.Serilog/issues/12 and [in this comment](https://github.com/Particular/NServiceBus/issues/4902#issuecomment-321693004).

![image](https://user-images.githubusercontent.com/950630/45525617-1d4acc80-b817-11e8-959c-771ed2b7f696.png)

I have tracked this down to the two `logger.BindProperty()` expressions in `SendMessageBehavior `:

![image](https://user-images.githubusercontent.com/950630/45525676-57b46980-b817-11e8-8131-c89328f54949.png)

Drilling-down into the `BindProperty` extension, you will see that Serilog's `BindProperty()` method is returning false and the returned `LogEventProperty` is therefore null:

![image](https://user-images.githubusercontent.com/950630/45525907-40c24700-b818-11e8-8d8e-b37ac30a7d0b.png)

Look forward to your feedback.
Craig.

**Comment by Craigology** [comment]
Thanks for the fast turnaround @SimonCropp, will try it out and confirm.

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
