### ISSUE TITLE
System.InvalidCastException after updating from 7.0.0 to 7.1.0

### ISSUE THREAD

**Issue by ericburcham-eprod** [NServiceBusExtensions/NServiceBus.Serilog#277]
After updating from 7.0.0 to 7.1.0, I am consistently getting the following exception when one of my services starts up:
```
Application InterfacesTopHatAdapterService exiting: Terminating InterfacesTopHatAdapterService TDESTREAM67CORP due to extended endpoint outage.
System.InvalidCastException: **_Unable to cast object of type 'System.DateTime' to type 'System.String'_**.
   at ExceptionExtensions.TryReadData[T](Exception exception, String key, T& state) in C:\projects\nservicebus-serilog\src\NServiceBus.Serilog\ExceptionExtensions.cs:line 12
   at Logger.WriteExceptionEvent(String message, Exception exception, LogEventLevel level) in C:\projects\nservicebus-serilog\src\NServiceBus.Serilog\Logger.cs:line 34
   at NServiceBus.RecoverabilityExecutor.<DeferMessage>d__4.MoveNext() in C:\BuildAgent\work\38c4d2c8fb0bd52a\src\NServiceBus.Core\Recoverability\RecoverabilityExecutor.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.Transport.RabbitMQ.MessagePump.<Process>d__29.MoveNext() in C:\BuildAgent\work\15dcdbe5f88af6ed\src\NServiceBus.Transport.RabbitMQ\Receiving\MessagePump.cs:line 263
```
**NOTE**:  The talk about "Extended endpoint outage" is just a bad error message in the OnCriticalError method of our endpoint configuration builder.  It attaches that message every time and endpoint fails to connect.  This, it turns out, is an incorrect assumption and will be fixed in our next build.  The _real_ Exception _is_ coming from NServiceBus.Serilog.

I notice, in the following comparison, that several of the methods in Logger have been changed so the out variable is a string instead of a DateTime.  Perhaps this is the source of the error.

https://github.com/NServiceBusExtensions/NServiceBus.Serilog/compare/NServiceBusExtensions:7.0.0...7.1.0

Also, I don't know where you stand on the age-old argument of whether a logger should ever throw, but I was personally surprised to see an Exception bubbling up from a logger assembly in any case.  I have always been on the "loggers should provide a no-throw guarantee" side of that particular fence.

Cheers, and thanks for all the hard work.

**Comment by SimonCropp** [comment]
i will look at this today. just to confirm, are all devs (using this extension) at your company patrons? https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq

**Comment by ericburcham-eprod** [comment]
> i will look at this today. just to confirm, are all devs (using this extension) at your company are patrons? https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq

No.

**Comment by ericburcham-eprod** [comment]
I’m actually very interested to discuss how the Patron thing is going for you, and look at how we might support you.  But I can’t do so on a public channel.  Is there a way I can reach you to discuss privately?

**Comment by SimonCropp** [comment]
simon.cropp@gmail.com

**Comment by SimonCropp** [comment]
what version of NSB are you using. since version 7.3 the info in the exception data has been strings https://github.com/Particular/NServiceBus/commit/7879f8f1a554290dbb1a3b467ea9ff3c2400e725#diff-abf6bd55932856e7e8c45b5eeaef159e  

So i dont understand how you have strings in that data.

If you are using version 7.3, can you provide a way to reproduce this problem

**Comment by SimonCropp** [comment]
bump

**Comment by ericburcham-eprod** [comment]
I'm going to chalk this up to something on our end.  The services start 100% of the time when running locally.  They fail about 30% of the time running after deployment.  I'll bet something somewhere is failing to properly clear out the deployment folder, and an older DLL is hanging around.  Either that, or somebody somewhere has a DLL reference instead of a Nuget reference.

To answer you question, for these builds we were running NSB 7.3.0.  Rolling NSB.Serilog back to 7.0.0 and NSB back to 7.2.2 fixes the problem.  I'm going to remove _all_ the NSB references and re-add them manually with nuget to the updated versions.  That will eliminate any inconsistency in the way people have added references.  If that fails, I'll look with great detail into our deployments, even though that isn't my bally-wick.  If I'm able to actually isolate the problem so this project, I will open a new issue.

Thanks for playing.

**Comment by SimonCropp** [comment]
@ericburcham-eprod and re this ? https://github.com/NServiceBusExtensions/NServiceBus.Serilog/issues/277#issuecomment-671507642
