### ISSUE TITLE
Exception enrichment logs entire message payload while doing retries

### ISSUE THREAD

**Issue by NitinM3** [NServiceBusExtensions/NServiceBus.Serilog#298]
I noticed that Exception enrichment logs the entire payload in logs (application insights). Is there any way to restrict enricher being log the entire payload as message payload may contain sensitive (PHI and PII) data.

`IncomingMessage- {"EventName":"testpatientcreatedevent","Body":"{\"id\":43451789,\"Address\":{\"Address1\":\"consequat mollit in ut pariatur\",\"Address2\":\"ipsum Lorem\"},\"DateOfBirth\":\"1962-01-30T19:52:49.445Z\",\"HasCancer\":false,\"PatientInfo\":[\"labore quis cupidatat\"],\"PatientName\":\"34b219e1-5116-499c-a68b-58cce8fb29d9\",\"Weight\":100.0}","_typeTag":"GenericEvent"}`

**Comment by SimonCropp** [comment]
note that to be using this you need to be a patron on opencollective https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq
