### ISSUE TITLE
"Normal" exceptions are not being logged anymore

### ISSUE THREAD

**Issue by masterpoi** [NServiceBusExtensions/NServiceBus.Serilog#36]
```csharp
          LogManager.GetLogger("Test").Error("Some", new Exception("Error"));
```
Logs
```
[2018-11-22 20:24:03.306 ERR] <1> Some
```

due to the check here

https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/ba591eec8e7da1dffe5f59f9fe12f9d716e6e658/NServiceBus.Serilog/Logger.cs#L23

Expected outcome:

```
[2018-11-22 20:24:03.306 ERR] <1> Some
System.Exception: Error
```

**Comment by SimonCropp** [comment]
this is now deployed

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
