### ISSUE TITLE
Exceptions not logged by RecoverabilityExecutor unless tracing enabled

### ISSUE THREAD

**Issue by espenwa** [NServiceBusExtensions/NServiceBus.Serilog#37]
Running NServicebus 7.1.4 with NServiceBus.Serilog 6.1.2 under .net core 2.1 (with generic host/IHostBuilder), and logging-level set to Debug.
Possibly related to #36 ?

When an exception is thrown in a handler, the exception-info is not logged.

Only message logged by the RecoverabilityExecutor is: 
> 2018-11-24 00:22:42 INF Immediate Retry is going to retry message '6a8642c0-1d42-4c6c-b0b9-a9a10178a972' because of an exception:

When turning on tracing using
```c#
var serilogTracing = endpointConfiguration.EnableSerilogTracing(logger);
serilogTracing.EnableMessageTracing();
```
... the exception is logged:
> 2018-11-24 00:25:28 INF Immediate Retry is going to retry message '6a8642c0-1d42-4c6c-b0b9-a9a10178a972' because of an exception:
> System.Exception: Test-exception thrown in handler!
>   at TestEndpointCore.TestHandler.Handle(TestCommand message, IMessageHandlerContext context)
> [...]```

When using default logger the exception is logged without enabling tracing.

**Comment by SimonCropp** [comment]
can u try with 6.1.3

**Comment by espenwa** [comment]
Looks like it works now - thanks!

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
